<?php
// --- Konfiguracja: lista sklepów i produktów ---
return [
'Ziko' => [
        ['name' =>'Tira','unit' =>'op.'],
        ['name' =>'Eco Rolls','unit' =>'op.'],
        ['name' =>'Len Mielony','unit' =>'op.'],
        ['name' =>'Ciasteczka Owsiane Naturalne','unit' =>'op.'],
        ['name' =>'Dżem Malinowy','unit' =>'op.'],
        ['name' =>'Powidła Śliwkowe','unit' =>'op.'],
        ['name' =>'Figi suszone','unit' =>'op.'],
		['name' =>'Przyprawy','unit' =>'temat'],
        ['name' =>'Pektosól','unit' =>'op.'],
        ['name' =>'Maggi','unit' =>'op.'],
        ['name' =>'Pieprz Czarny','unit' =>'op.'],
        ['name' =>'Granat','unit' =>'szt.'],
        ['name' =>'Pomidory','unit' =>'szt.'],
        ['name' =>'Ziemniaki','unit' =>'kg'],
        ['name' =>'Kapusta Biała','unit' =>'szt.'],
        ['name' =>'Cytryna','unit' =>'szt.'],
        ['name' =>'Pieczarki','unit' =>'szt.'],
        ['name' =>'Winogrona','unit' =>'kiść'],
        ['name' =>'Marchew+Pietruszka+Seler','unit' =>'zest.'],
        ['name' =>'Buraki','unit' =>'szt.'],
        ['name' =>'Cebula Drobna','unit' =>'szt.'],
        ['name' =>'Czosnek','unit' =>'szt.'],
        ['name' =>'Kapusta Kiszona','unit' =>'porc.'],
		['name' =>'Papryka czerwona','unit' =>'szt.'],
        ['name' =>'Ogórki Kiszone','unit' =>'op.'],
        ['name' =>'Jabłko','unit' =>'szt.'],
        ['name' =>'Maślanka','unit' =>'op.'],
        ['name' =>'Zott','unit' =>'op.'],
        ['name' =>'Mleko','unit' =>'op.'],
        ['name' =>'Kefir Góralik','unit' =>'op.'],
        ['name' =>'Kwaśne Mleko','unit' =>'op.'],
        ['name' =>'Śmietana','unit' =>'op.'],
        ['name' =>'Śmietana Mała','unit' =>'op.'],
        ['name' =>'Ser Biały','unit' =>'op.'],
        ['name' =>'Masło Mońki','unit' =>'kost.'],
        ['name' =>'Masło Polskie','unit' =>'kost.'],
        ['name' =>'Camembert','unit' =>'op.'],
        ['name' =>'Delicje Pomarańczowe','unit' =>'op.'],
        ['name' =>'Familijne Gofrowe Czekoladowe','unit' =>'op.'],
        ['name' =>'Maltanki','unit' =>'op.'],
        ['name' =>'Słomka','unit' =>'op.'],
        ['name' =>'Biszkopty','unit' =>'op.'],
        ['name' =>'Herbatniki Krakuski','unit' =>'op.'],
        ['name' =>'Majonez','unit' =>'op.'],
        ['name' =>'Czekolada Z Orzechami','unit' =>'op.'],
        ['name' =>'Krówka Mleczna','unit' =>'op.'],
        ['name' =>'Cukier','unit' =>'op.'],
        ['name' =>'Sól','unit' =>'op.'],
        ['name' =>'Kasza Jęczmienna Średnia','unit' =>'op.'],
        ['name' =>'Kasza Gryczana Szczytno','unit' =>'op.'],
        ['name' =>'Grysik','unit' =>'op.'],
        ['name' =>'Ryż','unit' =>'op.'],
        ['name' =>'Makaron Nitka Cienka','unit' =>'op.'],
        ['name' =>'Makaron Wstążka','unit' =>'op.'],
        ['name' =>'Herbata Yunan','unit' =>'op.'],
        ['name' =>'Earl Gray','unit' =>'op.'],
        ['name' =>'Assam','unit' =>'op.'],
		['name' =>'Płatki owsiane błyskawiczne (zielone)','unit' =>'op.'],
        ['name' =>'Pierś Z Kurczaka','unit' =>'szt.'],
        ['name' =>'Coś Na Obiad','unit' =>':-)'],
        ['name' =>'Olej Kujawski','unit' =>'op.'],
        ['name' =>'Weka','unit' =>'szt.'],
		['name' =>'Kajzerki','unit' =>'szt.'],
		['name' =>'Bułki z kropkami na spodzie','unit' =>'szt.'],
        ['name' =>'Sucharki','unit' =>'op.'],
        ['name' =>'Tekturki','unit' =>'op.'],
        ['name' =>'Mydło','unit' =>'op.'],
        ['name' =>'Proszek E Kolor','unit' =>'op.'],
        ['name' =>'Dezodorant Nivea Fresh Nautural 0%','unit' =>'op.'],
        ['name' =>'Krem Do Rąk Ziaja Kozie Mleko','unit' =>'op.'],
        ['name' =>'Gąbki Do Naczyń','unit' =>'op.'],
        ['name' =>'Chusteczki Hig.','unit' =>'op.'],
        ['name' =>'Ludwik','unit' =>'op.'],
        ['name' =>'Paluszki Duże','unit' =>'op.'],
        ['name' =>'Piwo','unit' =>'but.'],
        ['name' =>'Muszynianka','unit' =>'but.'],
        ['name' =>'Zapalniczka','unit' =>'szt.']
    ],
'Biała budka' => [
        ['name' => 'Gazeta', 'unit' => 'szt.'],
        ['name' => 'Szampon tatarak', 'unit' => 'op.'],
        ['name' => 'Płyn micelarny Lirene', 'unit' => 'op.'],
        ['name' => 'Krem Biała Perła', 'unit' => 'op.'],
		['name' => 'Parodontax', 'unit' => 'op.']
    ],    

'Henio' => [
        ['name' => 'Imbir', 'unit' => 'dag'],
        ['name' => 'Żurawina', 'unit' => 'dag'],
        ['name' => 'Goji', 'unit' => 'dag'],
        ['name' => 'Migdały', 'unit' => 'szt.'],
		['name' =>'Figi suszone','unit' =>'op.']
    ],
'Koleś' => [
        ['name' => 'Jaja wiejskie małe', 'unit' => 'op. 10 szt.'],
        ['name' => 'Jaja wiejskie duże', 'unit' => 'op. 6 szt.'],
        ['name' => 'Ziemniaki', 'unit' => 'kg'],
        ['name' => 'Truskawki', 'unit' => 'dag'],
        ['name' => 'Winogrona', 'unit' => 'kiść'],
        ['name' => 'Pieczarki', 'unit' => 'szt.'],
        ['name' => 'Pomidory', 'unit' => 'szt.']
    ],
'Apteka' => [
        ['name' => 'Urosept', 'unit' => 'op.']
    ],
'Lidl' => [
        ['name' =>'Owoce','unit' =>'szt.'],
        ['name' =>'Kapusta Pekińska','unit' =>'szt.'],
        ['name' =>'Marchew','unit' =>'szt.'],
        ['name' =>'Cebula dymka','unit' =>'wiązka'],
        ['name' =>'Koper włoski','unit' =>'szt.'],
        ['name' =>'Galaretki','unit' =>'dag'],
        ['name' =>'Trufle','unit' =>'dag'],
        ['name' =>'Krówki','unit' =>'op.'],
		['name' =>'Figi suszone','unit' =>'op.'],
        ['name' =>'Wafelki Czekoladowe','unit' =>'op.'],
        ['name' =>'Delicje','unit' =>'op.'],
        ['name' =>'Grissini','unit' =>'op.'],
        ['name' =>'Coca-Cola','unit' =>'op.'],
        ['name' =>'Gąbki','unit' =>'op.'],
        ['name' =>'Ściereczki Do Okularów','unit' =>'op.'],
        ['name' =>'Kaparki','unit' =>'op.'],
        ['name' =>'Olej Lniany Ola','unit' =>'op.'],
        ['name' =>'Penne','unit' =>'op.'],
        ['name' =>'Spaghetti','unit' =>'op.'],
    ],
'SELGROS' => [
        ['name' =>'Ubrania','unit' =>'temat'],
        ['name' =>'Biurowe','unit' =>'temat'],
        ['name' =>'Kalendarz terminarz','unit' =>'szt.'],
        ['name' =>'Auto','unit' =>'temat'],
        ['name' =>'Dynagel','unit' =>'op.'],
        ['name' =>'Ziemia','unit' =>'op.'],
        ['name' =>'Maciejka','unit' =>'op.'],
        ['name' =>'Owies','unit' =>'op.'],
        ['name' =>'Sitko Kuchenne 20 Cm Profi Line Hendi','unit' =>'szt.'],
        ['name' =>'Taśma Czerwono-Biała','unit' =>'szt.'],
        ['name' =>'Gąbka Do Mopa','unit' =>'szt.'],
        ['name' =>'Ciasteczka Zbożowe','unit' =>'op.'],
        ['name' =>'Kasza Manna','unit' =>'op.'],
        ['name' =>'Cantuccini','unit' =>'op.'],
        ['name' =>'Prince Polo','unit' =>'op.'],
        ['name' =>'Kasza Owsiana','unit' =>'op.'],
        ['name' =>'Paluszki Słone','unit' =>'op.'],
        ['name' =>'Amarantus','unit' =>'op.'],
        ['name' =>'Płatki Jaglane','unit' =>'op.'],
        ['name' =>'Płatki Ryżowe','unit' =>'op.'],
        ['name' =>'Czekolada Z Orzechami','unit' =>'op.'],
        ['name' =>'Makaron Wielicki','unit' =>'op.'],
        ['name' =>'Makaron Ryżowy','unit' =>'op.'],
        ['name' =>'Chałwa','unit' =>'op.'],
        ['name' =>'Prezent','unit' =>'op.'],
        ['name' =>'Spaghetti','unit' =>'op.'],
        ['name' =>'Makaron','unit' =>'op.'],
        ['name' =>'Penne','unit' =>'op.'],
        ['name' =>'Ferrero','unit' =>'op.'],
        ['name' =>'Dżem Pomar.','unit' =>'op.'],
        ['name' =>'Dzem Różany','unit' =>'op.'],
        ['name' =>'Powidła Śliwkowe Tenczynek','unit' =>'op.'],
        ['name' =>'Chia','unit' =>'op.'],
		['name' =>'Figi suszone','unit' =>'op.'],
        ['name' =>'Kapary','unit' =>'op.'],
        ['name' =>'Oliwki','unit' =>'op.'],
        ['name' =>'Przyprawy','unit' =>'temat'],
        ['name' =>'Oregano','unit' =>'op.'],
        ['name' =>'Papryka Słodka','unit' =>'op.'],
        ['name' =>'Papryka Ostra','unit' =>'op.'],
        ['name' =>'Kmin Rzymski Cały','unit' =>'op.'],
        ['name' =>'Pieprz czarny mielony','unit' =>'op.'],
        ['name' =>'Pieprz czarny ziarnisty','unit' =>'op.'],
        ['name' =>'Pieprz czarny GRUBO mielony','unit' =>'op.'],
        ['name' =>'Pesto','unit' =>'op.'],
        ['name' =>'Knorr Mix Gulasz Węgierski','unit' =>'op.'],
        ['name' =>'Pieprz Grubo Mielony','unit' =>'op.'],
        ['name' =>'Peperoni ','unit' =>'op.'],
        ['name' =>'Pomidory W Puszcze','unit' =>'op.'],
        ['name' =>'Proszek Do Pieczenia','unit' =>'op.'],
        ['name' =>'Cukier Wanil.','unit' =>'op.'],
        ['name' =>'Koncentrat Pomidorowy','unit' =>'op.'],
        ['name' =>'Oliwa','unit' =>'op.'],
        ['name' =>'Olej','unit' =>'op.'],
        ['name' =>'Ocet','unit' =>'op.'],
        ['name' =>'Chrzan','unit' =>'op.'],
        ['name' =>'Majonez','unit' =>'op.'],
        ['name' =>'Musztarda','unit' =>'op.'],
        ['name' =>'Barszcz Czerwony Krakus','unit' =>'op.'],
        ['name' =>'Yunan','unit' =>'op.'],
        ['name' =>'Assam','unit' =>'op.'],
        ['name' =>'Earl Gray ','unit' =>'op.'],
        ['name' =>'Kopiko','unit' =>'op.'],
        ['name' =>'Kawa','unit' =>'op.'],
        ['name' =>'Kakao','unit' =>'op.'],
        ['name' =>'Sól','unit' =>'op.'],
        ['name' =>'Cukier','unit' =>'op.'],
        ['name' =>'Granat','unit' =>'op.'],
        ['name' =>'Cytryna','unit' =>'op.'],
        ['name' =>'Batat','unit' =>'op.'],
        ['name' =>'Brzoskwinie Rolnik','unit' =>'op.'],
        ['name' =>'Ryba','unit' =>'op.'],
        ['name' =>'Sok Piniowy','unit' =>'op.'],
        ['name' =>'Sos Sojowy Ciemny','unit' =>'op.'],
        ['name' =>'Camembert','unit' =>'op.'],
        ['name' =>'Camembert Ola','unit' =>'op.'],
        ['name' =>'Papryka W Tubce','unit' =>'op.'],
        ['name' =>'Mascarpone','unit' =>'op.'],
        ['name' =>'Mozzarella','unit' =>'op.'],
        ['name' =>'Jogurt Grecki','unit' =>'op.'],
        ['name' =>'Mleko Bio','unit' =>'op.'],
        ['name' =>'Śmietana 18%','unit' =>'op.'],
        ['name' =>'Mleko Kwaśne','unit' =>'op.'],
        ['name' =>'Masło','unit' =>'op.'],
        ['name' =>'Drożdże','unit' =>'op.'],
        ['name' =>'Grana Padano','unit' =>'op.'],
        ['name' =>'Mineralne','unit' =>'op.'],
        ['name' =>'Piwo Lech 0%','unit' =>'op.'],
        ['name' =>'Wino','unit' =>'op.'],
        ['name' =>'Amaretto','unit' =>'op.'],
        ['name' =>'Wyborowa','unit' =>'op.'],
        ['name' =>'Chusteczki Hig.','unit' =>'op.'],
        ['name' =>'Płyny Do Prania','unit' =>'op.'],
        ['name' =>'Ajax Proszek','unit' =>'op.'],
        ['name' =>'Cif','unit' =>'op.'],
        ['name' =>'Cleanlux','unit' =>'op.'],
        ['name' =>'Mydło','unit' =>'op.'],
        ['name' =>'Papier Toaletowy Foxy Cotton','unit' =>'op.'],
        ['name' =>'Kret','unit' =>'op.'],
        ['name' =>'Żel Do Wc','unit' =>'op.'],
        ['name' =>'Sidolux Płyn Do Pcv','unit' =>'op.'],
        ['name' =>'Sidolux Płyn Do Terakoty','unit' =>'op.'],
        ['name' =>'Gąbki Do Zmywania','unit' =>'op.'],
        ['name' =>'Mydło Marsylskie','unit' =>'op.'],
        ['name' =>'Ziaja Krem Q Enzym','unit' =>'op.'],
        ['name' =>'Ziaja Krem Oliwkowy','unit' =>'op.'],
        ['name' =>'Bambino','unit' =>'op.'],
        ['name' =>'Ludwik','unit' =>'op.'],
        ['name' =>'Pasta Do Butów','unit' =>'op.'],
        ['name' =>'Deo Ziaja Active','unit' =>'op.'],
        ['name' =>'Szampon ','unit' =>'op.'],
        ['name' =>'Worki Na Śmieci','unit' =>'op.'],
        ['name' =>'Worki Śniadaniowe','unit' =>'op.'],
        ['name' =>'Aronal','unit' =>'op.'],
        ['name' =>'Parodontax Extra Fresh','unit' =>'op.'],
        ['name' =>'Elektrolity','unit' =>'op.'],
        ['name' =>'Ace','unit' =>'op.'],
        ['name' =>'Bang Kamień I Rdza','unit' =>'op.']
	]
];
